name: DownDating
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:                    # ← Only ONE flutter: section
  uses-material-design: true
  assets:                   # ← Add assets here under existing flutter:
    - assets/images/